# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  name: 'Restore' 
  displayName: 'Restaurando Paquetes y dependencias'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: 'c02610e3-ed5a-4422-8dfc-732f5bdef937'
    verbosityRestore: 'Normal'

- task: DotNetCoreCLI@2
  name: 'Build'
  displayName: 'Compilando Carrow'
  inputs:
    command: 'build'
    projects: 'Carrow/*.csproj'
    arguments: '--no-restore --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  name: 'BuildTest'
  displayName: 'Compilando CarrowTest'
  inputs:
    command: 'build'
    projects: 'CarrowTest/*.csproj'
    arguments: '--no-restore --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  name: 'Testing'
  displayName: 'Unit testing Carrow'
  inputs:
    command: 'test'
    projects: 'CarrowTest/*.csproj'
    arguments: '--no-build --configuration $(buildConfiguration)'
    testRunTitle: 'Carrow Test'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -#kSL -o ./Carrow/Docs/template.tar.gz https://github.com/jbltx/DiscordFX/archive/v0.3.tar.gz
      tar xvfz Carrow/Docs/template.tar.gz -C ./Carrow/Docs
      mkdir ./Carrow/Docs/templates
      mv Carrow/Docs/DiscordFX-0.3/discordfx ./Carrow/Docs/templates/discordfx

- task: DocFxTask@0
  inputs:
    solution: 'Carrow/Docs/docfx.json'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      tar cvfz site.tar.gz ./Carrow/Docs/_site
      mv site.tar.gz $(Build.ArtifactStagingDirectory)/packs
      
- task: DotNetCoreCLI@2
  name: 'Packaging'
  displayName: 'Empacando Carrow'
  inputs:
    command: 'pack'
    packagesToPack: 'Carrow/*.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)/packs'
    nobuild: true
    includesource: true
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '0'
    minorVersion: '1'
    patchVersion: '0'
    verbosityPack: 'Normal'

- task: PublishBuildArtifacts@1
  name: 'Droping' 
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/packs'
    ArtifactName: 'drop'
    publishLocation: 'Container'